# Context

Fisheries and Oceans Canada (DFO) has conducted Summer Research Vessel (RV) surveys in the Maritimes Region, Northwest Atlantic Fisheries Organization (NAFO) Divisions 4VWX5Yb, using a standardized protocol since 1970 (Figure\@ref(fig:1-map-NAFO)). Results of these surveys provide information on trends in abundance for most groundfish species in the Maritimes Region. While these data reflect trends in biomass and abundance and are a critical part of science-based stock assessments, a full assessment, including other sources of data, would be required to evaluate the impacts of management measures on population status. Resource Management requested a review of the DFO RV Survey information on the following list of fish stocks: 4Vn, 4VsW, and 4X5Y Atlantic Cod; 4VW and 4X5Y Haddock; 4X and 4VW White Hake; 4VWX Silver Hake; 4VWX+5 Pollock; Unit II and Unit III redfish; 3NOPs4VWX5Zc Atlantic Halibut; 4VW and 4X American Plaice; 4VW and 4X Witch Flounder; 4VW and 4X Winter Flounder; 4VW and 4X Yellowtail Founder; 4VW and 4X Smooth Skate; 4VW and 4X Thorny Skate; 4VW and 4X Barndoor Skate; 4VW and 4X Winter Skate; 4VW and 4X Little Skate; 4VW and 4X Atlantic Wolffish; 4VW and 4X Monkfish; 4VW and 4X Longhorn Sculpin; 4VWX Spiny Dogfish; 4X and 4VW Red Hake; 4X and 4VW Sea Raven; 4X and 4VW Ocean Pout. In addition, biomass trends relative to the Scotia Fundy Groundfish Advisory Committee (SFGAC) accepted biomass reference points were requested for White Hake (biomass for lengths >41 cm in 4X) and Unit III redfish (biomass for lengths >22 cm). The survey information will be used by DFO Resource Management as background for discussions with various stakeholders on recommendations for management measures and to determine which stocks should be reviewed in more detail in 2020.

In addition, a review of available survey information was undertaken for a suite of species, including Blackbelly Rosefish, Black Sea Bass, Dusky Shark, Triggerfish, John Dory, and Tilefish. These species are being captured as bycatch in commercial fishing operations but are not covered under any license conditions and cannot be landed. This Science Response Report results from the Science Response Process of December 4–5, 2019, on the Maritimes Research Vessel Survey Trends on the Scotian Shelf and Bay of Fundy.

Additional publications from this meeting will be posted on the \href{http://www.isdm-gdsi.gc.ca/csas-sccs/applications/events-evenements/index-eng.asp}{DFO Science Advisory Schedule} as they become available.

